PACKAGE_NAME="eleven-rack"
PACKAGE_VERSION="@VERSION@"
BUILT_MODULE_NAME[0]="snd-usb-audio"
BUILT_MODULE_LOCATION[0]="kernel-source/sound/usb"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="bash build-driver.sh ${kernelver} ${kernel_source_dir}"
CLEAN="true"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL="^(6\.(8|9|[1-9][0-9])|[7-9]\.[0-9]+)\."
